version: "3.8"
services:
  api-endpoint:
    build:
      dockerfile: ./api-endpoint/Dockerfile
    env_file:
      - ./.env.api-endpoint
    ports:
      - "${API_ENDPOINT_PORT}:${API_ENDPOINT_PORT}"
    depends_on:
      - user
      - email
      - templating
    environment:
      - SERVICE_URL=[::0]
      - SERVICE_PORT=${API_ENDPOINT_PORT}
      - USER_HOST=http://host.docker.internal
      - USER_PORT=${USER_SERVICE_PORT}
      - EMAIL_HOST=http://host.docker.internal
      - EMAIL_PORT=${EMAIL_SERVICE_PORT}
      - TEMPLATING_HOST=http://host.docker.internal
      - TEMPLATING_PORT=${TEMPLATING_SERVICE_PORT}
  user:
    build:
      dockerfile: ./user/Dockerfile
    env_file:
      - ./.env.user
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    depends_on:
      - database
    environment:
      - SERVICE_URL=[::0]
      - SERVICE_PORT=${USER_SERVICE_PORT}
  email:
    build:
      dockerfile: ./email/Dockerfile
    env_file:
      - ./.env.email
    ports:
      - "${EMAIL_SERVICE_PORT}:${EMAIL_SERVICE_PORT}"
    depends_on:
      - database
    environment:
      - SERVICE_URL=[::0]
      - SERVICE_PORT=${EMAIL_SERVICE_PORT}
  templating:
    build:
      dockerfile: ./templating/Dockerfile
    env_file:
      - ./.env.templating
    ports:
      - "${TEMPLATING_SERVICE_PORT}:${TEMPLATING_SERVICE_PORT}"
    depends_on:
      - database
    environment:
      - SERVICE_URL=[::0]
      - SERVICE_PORT=${TEMPLATING_SERVICE_PORT}
  database:
    image: postgres:15.3
    volumes:
      - ./multi-database:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_MULTIPLE_DATABASES}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
volumes:
  database:
    driver: local
